### ISSUE TITLE
与lattice-faster-decoder解码不一致

### ISSUE THREAD

**Issue by Sundy1219** [xiangxyq/minimize-chain-decoder#2]
您好，
　　您的工程非常好，我这边也跑通了，用自己的模型也没问题.我发现您这个decoder是根据lattice-faster-decoder裁剪的．您有验证过两者的一致性吗？我用同一个wav，同样的模型，同样的解码参数，您的mini decoder和kaldi的lattice-faster-decoder解码有差异，有的wav差异较大，解码会出现解码帧数会比lattice-faster-decoder少.　期待您的解答，谢谢!!!!

**Comment by zw76859420** [comment]
您好，我也遇到了上述提问者一样的问题，请您帮忙看看什么原因？谢谢

**Comment by xiangxyq** [comment]
> 您好，我也遇到了上述提问者一样的问题，请您帮忙看看什么原因？谢谢

出现这种情况的原因，应该是音频长度是超过2s的，代码写的类似离线实现的方式，每次取完2s的音频，再取下一个2s音频的时候reset了，会和online提取特征有点差异，你可以修改成流式解码的形式，就不会出现这样的情况

**Comment by zw76859420** [comment]
> > 您好，我也遇到了上述提问者一样的问题，请您帮忙看看什么原因？谢谢
> 
> 出现这种情况的原因，应该是音频长度是超过2s的，代码写的类似离线实现的方式，每次取完2s的音频，再取下一个2s音频的时候reset了，会和online提取特征有点差异，你可以修改成流式解码的形式，就不会出现这样的情况

明白了，谢谢陈老师
再请教下，您这边有支持 vs 调试的版本吗？

**Comment by zw76859420** [comment]
跟进一个问题，请问我可以将时间设置为16s进行解码吗？
我这边已经在windows 本地配置完成 openfst 与 openblas的版本

**Comment by xiangxyq** [comment]
vs版本我没有验证过，对于时间设置成16s的话，建议最好改成流式解码，不然结果要等16s后才会出来，响应会比较慢

**Comment by xiangxyq** [comment]
openfst和openblas可以使用kaldi windows编译说明中提供的版本

**Comment by zw76859420** [comment]
流式解码确实如此，16s解码耗时大于16s，但是请问大佬是否可以参考kaldi中nnet3 离线解码改装您现有的流式代码？

**Comment by zw76859420** [comment]
多谢陈老师，劳烦可以加您的微信吗？我的微信号是：15026778796，劳烦您加下，共同讨论语音技术，谢谢

**Comment by xiangxyq** [comment]
> 流式解码确实如此，16s解码耗时大于16s，但是请问大佬是否可以参考kaldi中nnet3 离线解码改装您现有的流式代码？

参考这个， 不过没有做精简操作
https://blog.csdn.net/cj1989111/article/details/115344323
https://github.com/xiangxyq/kaldi_rt_decoder

**Comment by zw76859420** [comment]
多谢多谢
